# Generated by Django 5.1.7 on 2025-03-24 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ClinicalsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "componentName",
                    models.CharField(
                        choices=[
                            ("hw", "Height/Weight"),
                            ("bp", "Blood Pressure"),
                            ("heartrate", "Heart Rate"),
                        ],
                        max_length=100,
                    ),
                ),
                ("componentValue", models.CharField(max_length=100)),
                ("measuredDataTime", models.DateTimeField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinicalsApp.patient",
                    ),
                ),
            ],
        ),
    ]
